from selenium.webdriver.common.by import By

class WorkLocators:
    REGISTRATION_BUTTON = By.XPATH, "//*[text()='Вход и регистрация']"
    NO_ACCOUNT_BUTTON = By.XPATH, "//*[text()='Нет аккаунта']"
    CREATE_ACCOUNT_BUTTON = By.XPATH, "//*[text()='Создать аккаунт']"
    ENTER_BUTTON = By.XPATH, "//button[contains(@class, 'buttonPrimary') and contains(text(), 'Войти')]"
    QUIT_BUTTON = By.CSS_SELECTOR, ".spanGlobal.btnSmall"
    CREATE_AD_BUTTON = By.XPATH, "//*[text()='Разместить объявление']"

    PROFILE_NAME_CSS = By.CSS_SELECTOR, ".profileText.name"
    PROFILE_IMAGE_CSS = By.CSS_SELECTOR, ".circleSmall"
    EMAIL_INPUT_XPATH = By.XPATH, "//input[@placeholder='Введите Email']"
    EMAIL_INPUT_ERROR_XPATH = By.XPATH, "//*[text()='Ошибка']"
    PASSWORD_INPUT_XPATH = By.XPATH, "//input[@placeholder='Пароль']"
    REPEAT_PASSWORD_XPATH = By.XPATH, "//input[@placeholder='Повторите пароль']"
    ADVERTISEMENT_AUTHORISATION_WINDOWS = By.XPATH, "//h1[text()='Чтобы разместить объявление, авторизуйтесь']"
    NAME_AD = By.XPATH, "//input[@name='name']"
    CATEGORIES_DROPDOWN = By.XPATH, "//div[@class='dropDownMenu_input__itKtw' and //input[@name='category']]/button[contains(@class, 'dropDownMenu_arrowDown__pfGL1')]"
    CATEGORIES_DROPDOWN_OPEN = By.XPATH, "//button[contains(@class, 'dropDownMenu_arrowUp__I25Xq')]"
    BOOK_CATEGORIES = By.XPATH, "//div[@class='dropDownMenu_options__CmHmm']/button[span[text()='Книги']]"
    STATEMENT_BU = By.XPATH, "//div[@class='radioUnput_inputRegular__FbVbr']"
    CITY_DROPDOWN = By.XPATH,".//div[@class='dropDownMenu_input__itKtw' and .//input[@name='city']]/button[contains(@class, 'dropDownMenu_arrowDown__pfGL1')]"
    CITY_DROPDOWN_OPEN = By.XPATH, ".//div[@class='dropDownMenu_options__CmHmm']"
    CITY = By.XPATH, "//div[contains(@class, 'dropDownMenu_options')]//button[.//span[text()='Новосибирск']]"
    DISCRIPTION = By.XPATH, "//textarea[@name='description']"
    PRICE = By.XPATH, "//input[@name='price']"
    PUBLISH_BUTTON = By.XPATH, "//button[text()='Опубликовать']"
    ENTER_TO_PROFILE = By.XPATH, "//button[contains(@class, 'circleSmall')]"
    MESSAGE_PUBLISH = By.XPATH, "//h2[contains(text(), 'Пылесос')]"
    PROFILE_AD_TEXT = By.XPATH, "//h1[contains(text(), 'Мои объявления')]"